### ISSUE TITLE
Publish connector as a Partner connector

### ISSUE THREAD

**Issue by bednar** [bonitoo-io/influxdb-gds-connector#2]
# Partner Connector requirements

https://developers.google.com/datastudio/connector/pscc-requirements

## Apps Script

1. [ ] [Share view access](https://support.google.com/drive/answer/2494822) of your Apps Script project with both of these addresses:
     - data-studio-contrib-qa@googlegroups.com
     - data-studio-contrib@google.com
1. [ ] [Create a deployment](https://developers.google.com/datastudio/connector/deploy#create_separate_deployments) named `Production` and update the `Production` deployment to contain the version of code you want to publish.
1. [ ] If you have updated your code since creating the `Production` deployment, ensure that the correct version of the code is selected for the deployment before you submit your connector.

## Manifest

You must include the following in your connector's manifest. View [manifest reference](https://developers.google.com/datastudio/connector/manifest) for more information about each property in manifest.

1. [ ] In `description`, make sure you provide all information and instructions necessary to have a basic understanding of the connector and how to use it. Connectors with vague and incomplete descriptions will be rejected during review.
1. [ ] `addOnUrl` should be a dedicated hosted page about your connector, preferably hosted on your own domain.
     - This page must contain or link to your **Privacy Policy** and **Terms of Use** hosted on the same domain as the addOnUrl.
     - This page should contain any details the user will need to know to use your connector.
     - If users need to sign up for an account to use your connector, the sign up link should be available from this page.
     - The page cannot be hosted at `https://sites.google.com/`.
     - See example pages from existing partners: [Funnel](https://funnel.io/marketing-reporting-google-data-studio), [Supermetrics](https://supermetrics.com/product/data-studio), [CallRail](https://www.callrail.com/integrations/googledatastudio/).
1. [ ] supportUrl should be a hosted page where users can go to get support for your connector. This cannot be an email or mailto link.
1. [ ] You should populate the `sources` property with all the sources your connector connects to. See [Sources in Manifest reference](https://developers.google.com/datastudio/connector/manifest#sources-ref) for details.
     - You can view the existing list of sources at our Data Registry Repository. If the source you are connecting to does not exist in the repository, send a pull request to the Data Registry Repository to add the source. Your connector will fail the review process if the sources in your manifest do not exist in the repository.
     - This is additional metadata for the connector that will be indexed for search feature in the gallery. You connector will show up in the search results when users search for a specific data source in the gallery.
     - The gallery will let users discover connectors by data sources by providing a Connectors by Data Source interface.
1. [ ] You should limit the number of endpoints called by `UrlFetchApp` in your connector to those absolutely required for connector functionality. Add the urlFetchWhitelist property to the root level of your manifest. View the urlFetchWhitelist reference for more info.
     - This property should contain all URLs your connector connects to using the `UrlFetchApp` call.
     - If your connector does not execute a `UrlFetchApp` call then set the property value to an empty list `[]`.
     - If your connector does not connect to a fixed domain or the endpoint prefix varies, omit the `urlFetchWhitelist` property in the manifest.
1. [ ] Manifest should contain values for `shortDescription`, `authType`, `feeType`, `privacyPolicyUrl`, and `termsOfServiceUrl`.
1. [ ] Connector `name` should be directly representative of what the connector specifically does. This makes it clear what the connector does and helps the user to identify the correct connector for their need.

## Template and report

1. [ ] If you connector has a fixed schema, [create a report template](https://developers.google.com/datastudio/connector/report-templates#how_to_create_a_report_template) for your connector and add it to the manifest. Enable Sharing by link for the report.
1. [ ] Create at least one demo report using your connector and [submit the report to Data Studio gallery](https://support.google.com/datastudio/answer/7540410?ref_topic=6291010). This report can be a replica of your template report or a separate report that displays even broader functionalities of your connector.
     - Adding the demo reports makes your connector eligible for promotional opportunities (getting featured, mentions in newsletters and blog posts, case studies etc).

## Connector

1. [ ] If the user needs an account to use the connector, make sure the connector `description` or the `addOnUrl` link provides instructions to help the user create one.
1. [ ] Your connector cannot be in unfinished or beta status. You have to publish a complete and functional connector. You can always update your connector but the production deployment that is released to users should be tested and feature complete.
1. [ ] Provide meaningful and actionable error messages to users when users encounter a [Connector internal error](https://developers.google.com/datastudio/connector/error-handling#connector-internal-error). This includes cases when a user provides invalid/blank input at configuration.
1. [ ] You connector's `shortDescription`, `description`, `addOnUrl` link, `supportUrl` link, and OAuth page (if applicable) should be free of spelling and grammatical errors.
1. [ ] Use appropriate authentication method in `getAuthType()`. Do not request credentials via `getConfig()`.
1. [ ] Complete the [OAuth Client Verification ](https://developers.google.com/apps-script/guides/client-verification) process. The verification is mandatory for all connectors regardless of the authentication method in getAuthType(). The verification process is handled by a separate team. Consult the [OAuth API Verification FAQ](https://support.google.com/cloud/answer/9110914) for more info on this. **Your connector will not be published if the OAuth Client Verification process is not completed.**
     - During the OAuth verification process, add your connector's required OAuth scopes as part of the OAuth consent screen configuration. If you fail to add all required scopes, you might pass the OAuth verification process but your connector will still show the Unverified app screen. This will cause the Partner Connector verification process to fail.
Authorize and test your connector using a new account after passing the OAuth verification process to ensure that Unverified app screen is not displayed to your users.
1. [ ] Ensure you adhere to the [Data Studio Galleries Terms of Service (Submitter)](https://support.google.com/datastudio/answer/7539411?ref_topic=7156687).

# TODO

**Comment by bednar** [comment]
### Privacy Policy 

- source: copy of https://www.influxdata.com/legal/privacy-policy/
- doc: [PRIVACY_POLICY.txt](https://github.com/bonitoo-io/influxdb-gds-connector/files/4868457/PRIVACY_POLICY.txt)

### Terms of Use

- source: copy of https://www.influxdata.com/legal/terms-of-use-influxdb-cloud-1/
- doc: [TERMS_OF_USE.txt](https://github.com/bonitoo-io/influxdb-gds-connector/files/4868425/TERMS_OF_USE.txt)

**Comment by russorat** [comment]
I have opened an issue with the marketing team to get the page created.

**Comment by russorat** [comment]
@bednar marketing page is ready here: https://www.influxdata.com/integration/google-data-studio/

**Comment by bednar** [comment]
Thanks @russorat, [appsscript.json](https://github.com/influxdata/influxdb-gds-connector/blob/master/src/appsscript.json) is updated to the new marketing page and I will continue with [OAuth Client Verification process](https://developers.google.com/apps-script/guides/client-verification).

**Comment by bednar** [comment]
The next step is **OAuth Client** verification - verify OAuth scopes of Google Apps Script. 

By verifying our Apps Script, we can remove the unverified app screen from authorization flow.

### Unverified script flow:

![unverified-app-ui](https://user-images.githubusercontent.com/455137/88626093-535f6580-d0aa-11ea-9080-c65ca361b883.gif)

### Requirements:

**Comment by tkyocum** [comment]
I've completed the items checked off above. Let me know if you need anything further!

**Comment by bednar** [comment]
@tkyocum thanks a lot

I've set the GCP project to [connector script](https://script.google.com/d/18YPFhvO1TMR7QFCw2iFuIH_1_iPvFIYrnT3fg8J7skoqUd5x7YAnPD7_/edit?usp=sharing) and sent **OAuth consent screen** to verification:

![Screenshot 2020-07-29 at 15 16 27](https://user-images.githubusercontent.com/455137/88804766-aae6f980-d1ae-11ea-9eb6-faeb589b03b8.png)

- https://console.cloud.google.com/apis/credentials/consent?project=gds-connector-284718

I hope that We will receive response in within 24 to 72 hours as is described here: https://developers.google.com/apps-script/guides/client-verification

**Comment by bednar** [comment]
Hi @tkyocum,

Google denied our request to verification, but without detail:

![Screenshot 2020-07-30 at 07 46 00](https://user-images.githubusercontent.com/455137/88885392-baab2000-d238-11ea-9608-245f96ca8352.png)


Maybe there is a problem with verification of `influxdata.com`

- Is the `influxdata.com` website verified through [Search Console](https://www.google.com/webmasters/tools/home)?
- Is a "owner" of `influxdata.com` a Project Owner or a Project Editor for our GCP project?

![Screenshot 2020-07-30 at 07 38 55](https://user-images.githubusercontent.com/455137/88884966-e8439980-d237-11ea-8134-2a3b51616a5b.png)

- https://support.google.com/cloud/answer/7454865?hl=en#verification

**Comment by tkyocum** [comment]
Double checked this and we are both verified correctly under my Influxdata.com account and I am an owner of the project with the same Influxdata.com account.

**Comment by bednar** [comment]
@tkyocum ok, thanks

**Comment by bednar** [comment]
The **OAuth Client Verification process** has been done:

![image](https://user-images.githubusercontent.com/455137/95546755-b3a34980-0a01-11eb-8c93-4d9de5442631.png)

Next step is create the demo report and submit the report to Data Studio gallery. 

- https://support.google.com/datastudio/answer/7540410?ref_topic=6291010
